// Code generated by protoc-gen-go. DO NOT EDIT.
// source: read_work.proto

package read_work

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Work struct {
	File                 string   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	TargetSubstring      string   `protobuf:"bytes,2,opt,name=targetSubstring,proto3" json:"targetSubstring,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Work) Reset()         { *m = Work{} }
func (m *Work) String() string { return proto.CompactTextString(m) }
func (*Work) ProtoMessage()    {}
func (*Work) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da7706f7097cf70, []int{0}
}

func (m *Work) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Work.Unmarshal(m, b)
}
func (m *Work) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Work.Marshal(b, m, deterministic)
}
func (m *Work) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Work.Merge(m, src)
}
func (m *Work) XXX_Size() int {
	return xxx_messageInfo_Work.Size(m)
}
func (m *Work) XXX_DiscardUnknown() {
	xxx_messageInfo_Work.DiscardUnknown(m)
}

var xxx_messageInfo_Work proto.InternalMessageInfo

func (m *Work) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *Work) GetTargetSubstring() string {
	if m != nil {
		return m.TargetSubstring
	}
	return ""
}

type LogLine struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Entry                string               `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LogLine) Reset()         { *m = LogLine{} }
func (m *LogLine) String() string { return proto.CompactTextString(m) }
func (*LogLine) ProtoMessage()    {}
func (*LogLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da7706f7097cf70, []int{1}
}

func (m *LogLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogLine.Unmarshal(m, b)
}
func (m *LogLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogLine.Marshal(b, m, deterministic)
}
func (m *LogLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogLine.Merge(m, src)
}
func (m *LogLine) XXX_Size() int {
	return xxx_messageInfo_LogLine.Size(m)
}
func (m *LogLine) XXX_DiscardUnknown() {
	xxx_messageInfo_LogLine.DiscardUnknown(m)
}

var xxx_messageInfo_LogLine proto.InternalMessageInfo

func (m *LogLine) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *LogLine) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

type WorkResult struct {
	Logs                 []*LogLine `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WorkResult) Reset()         { *m = WorkResult{} }
func (m *WorkResult) String() string { return proto.CompactTextString(m) }
func (*WorkResult) ProtoMessage()    {}
func (*WorkResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da7706f7097cf70, []int{2}
}

func (m *WorkResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkResult.Unmarshal(m, b)
}
func (m *WorkResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkResult.Marshal(b, m, deterministic)
}
func (m *WorkResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkResult.Merge(m, src)
}
func (m *WorkResult) XXX_Size() int {
	return xxx_messageInfo_WorkResult.Size(m)
}
func (m *WorkResult) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkResult.DiscardUnknown(m)
}

var xxx_messageInfo_WorkResult proto.InternalMessageInfo

func (m *WorkResult) GetLogs() []*LogLine {
	if m != nil {
		return m.Logs
	}
	return nil
}

func init() {
	proto.RegisterType((*Work)(nil), "Work")
	proto.RegisterType((*LogLine)(nil), "LogLine")
	proto.RegisterType((*WorkResult)(nil), "WorkResult")
}

func init() { proto.RegisterFile("read_work.proto", fileDescriptor_5da7706f7097cf70) }

var fileDescriptor_5da7706f7097cf70 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x8d, 0xa6, 0xd1, 0x4e, 0x0e, 0x85, 0xc5, 0x43, 0x08, 0xa2, 0x25, 0xa7, 0xe0, 0x61,
	0x0b, 0xf1, 0xe2, 0x03, 0xf4, 0xd8, 0xd3, 0x2a, 0x88, 0x27, 0x49, 0x70, 0xba, 0x2c, 0xdd, 0x66,
	0xca, 0xec, 0x04, 0xf1, 0xed, 0x25, 0x9b, 0xd6, 0x42, 0x4f, 0xbb, 0x33, 0xfb, 0xf1, 0xff, 0xdf,
	0xc2, 0x82, 0xb1, 0xfd, 0xfe, 0xfa, 0x21, 0xde, 0xe9, 0x03, 0x93, 0x50, 0xf9, 0x64, 0x89, 0xac,
	0xc7, 0x55, 0x9c, 0xba, 0x61, 0xbb, 0x12, 0xb7, 0xc7, 0x20, 0xed, 0xfe, 0x30, 0x01, 0xd5, 0x1a,
	0xd2, 0x0f, 0xe2, 0x9d, 0x52, 0x90, 0x6e, 0x9d, 0xc7, 0x22, 0x59, 0x26, 0xf5, 0xdc, 0xc4, 0xbb,
	0xaa, 0x61, 0x21, 0x2d, 0x5b, 0x94, 0xb7, 0xa1, 0x0b, 0xc2, 0xae, 0xb7, 0xc5, 0x75, 0x7c, 0xbe,
	0x5c, 0x57, 0x9f, 0x70, 0xbb, 0x21, 0xbb, 0x71, 0x3d, 0xaa, 0x57, 0x98, 0xff, 0x77, 0xc4, 0xb4,
	0xbc, 0x29, 0xf5, 0x64, 0xa1, 0x4f, 0x16, 0xfa, 0xfd, 0x44, 0x98, 0x33, 0xac, 0xee, 0x61, 0x86,
	0xbd, 0xf0, 0xef, 0xb1, 0x64, 0x1a, 0xaa, 0x67, 0x80, 0x51, 0xd0, 0x60, 0x18, 0xbc, 0xa8, 0x07,
	0x48, 0x3d, 0xd9, 0x50, 0x24, 0xcb, 0x9b, 0x3a, 0x6f, 0xee, 0xf4, 0xb1, 0xd5, 0xc4, 0x6d, 0x53,
	0x43, 0x36, 0xb2, 0xc8, 0xea, 0x11, 0xb2, 0x35, 0xc5, 0x8f, 0xcd, 0xf4, 0x78, 0x94, 0xb9, 0x3e,
	0xa7, 0x54, 0x57, 0x5d, 0x16, 0x55, 0x5e, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xcc, 0x13,
	0x7e, 0x31, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerClient interface {
	DoWork(ctx context.Context, in *Work, opts ...grpc.CallOption) (*WorkResult, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) DoWork(ctx context.Context, in *Work, opts ...grpc.CallOption) (*WorkResult, error) {
	out := new(WorkResult)
	err := c.cc.Invoke(ctx, "/Worker/DoWork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
type WorkerServer interface {
	DoWork(context.Context, *Work) (*WorkResult, error)
}

// UnimplementedWorkerServer can be embedded to have forward compatible implementations.
type UnimplementedWorkerServer struct {
}

func (*UnimplementedWorkerServer) DoWork(ctx context.Context, req *Work) (*WorkResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoWork not implemented")
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_DoWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Work)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).DoWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Worker/DoWork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).DoWork(ctx, req.(*Work))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoWork",
			Handler:    _Worker_DoWork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "read_work.proto",
}
